### ISSUE TITLE
shelldio cli

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#20]
Θα ήθελα να υπάρχει ένα cli που να προσφέρει

- [x] add <όνομα><σταθμός> #17
- [x] rm <όνομα><σταθμός> #18
- [x] list <όνομα><σταθμός> #19
- [x] help #22
- [x] version
- [x] update #21
- [x] Ενσωματωμένοι σταθμοί #14

Σημείωση: το help να παίζει για κάθε sub-command.

**Comment by drpaneas** [comment]
To Github δεν εχει concept για Epics. Αυτό το issue ειναι ένα epic issue.
Ανοιξε ξανά τα επιμέρους issues που έκλεισες και βάλε τα τα τα id τους εδώ, έτσι ώστε όταν γίνουν fixed, τότε θα κλείσει και αυτό το epic.

Δες: https://github.com/marketplace/actions/epic-issues-for-github

**Comment by cerebrux** [comment]
fixed with https://github.com/CerebruxCode/shelldio/pull/32
